Build UI
kennedyowusu/school-library pull request #4
Opened 2023-03-09 22:05 UTC by kennedyowusu

## Highlight

![217858384-6db97d5c-0dbd-4798-b9d2-1ad72d6cde84](https://user-images.githubusercontent.com/32777408/224170853-d3337f50-bf53-4d68-8867-22aa5fe174cd.gif)

- [ ] Add UI to the project to enable user interactivity
- [ ] Ensure all linters pass

2023-03-09 22:35 UTC, codecaiine commented
Hi @kennedyowusu  I sent you a message on slack

2023-03-09 22:36 UTC, kennedyowusu commented
I have responded just now please


On Thu, Mar 9, 2023 at 10:35 PM Yannick-Noel AKA ***@***.***>
wrote:

> Hi @kennedyowusu <https://github.com/kennedyowusu> I sent you a message
> on slack
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kennedyowusu/school-library/pull/4#issuecomment-1462921780>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH2CJQF6WMCKC4M5BXQ6W23W3JLLNANCNFSM6AAAAAAVVVRNJA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-09 23:39 UTC, codecaiine requested changes
Hi @kennedyowusu , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- UI well setup ✔️ 
- No rubocop errors ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 23:39 UTC, codecaiine commented on main.rb
> +def display_options
- [ ] Good job so far, your project is well required 👏 .  When I ran the application, I am getting an error as you can see below ⬇️ .  I think the **Uninitialized Constant Error**   referred to in code that can't be found, this error occurs. This often happens because the required method is missing, which is used to load another file and import all classes and method definitions from that file. Please fix it in order to make your app works in the same way as the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) . 👍 

![Capture](https://user-images.githubusercontent.com/6615394/224183812-81f91a71-0a31-4b81-a60f-427f9e6826db.PNG)

2023-03-10 08:58 UTC, kennedyowusu commented on main.rb
> +def display_options
The issue has been resolved. Thank for your suggestion @codecaiine

2023-03-10 09:01 UTC, kennedyowusu commented
The Issue identified by the previous reviewer has been resolved.

![Ruby-UI](https://user-images.githubusercontent.com/32777408/224271553-de5b6400-68aa-4702-91d4-1e2231498119.png)

2023-03-10 09:08 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @kennedyowusu, 

To highlight 👍🏽 
✔️ App runs smoothly
✔️ No linter errors
✔️ README is professional

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-03-10 09:28 UTC, merged